name: Commit Message Check

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5